-- UP
CREATE TABLE login(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password	TEXT NOT NULL
);

CREATE TABLE users(
	user_id	INTEGER	PRIMARY KEY,
	first_name	INTEGER NOT NULL,
	last_name	INTEGER	NOT NULL,
	email	TEXT	NOT NULL
);

-- DOWN

DROP TABLE LOGIN;
DROP TABLE USERS;
